/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package info.nicola.jeremy.pi4jdemo.view;

import javax.swing.JRadioButton;

/**
 *
 * @author jem
 */
public class PortFrame extends javax.swing.JFrame {

    /**
     * Creates new form PortFrame
     */
    public PortFrame() {
        initComponents();
    }

    public JRadioButton getPin0() {
        return pin0;
    }

    public JRadioButton getPin1() {
        return pin1;
    }

    public JRadioButton getPin10() {
        return pin10;
    }

    public JRadioButton getPin11() {
        return pin11;
    }

    public JRadioButton getPin12() {
        return pin12;
    }

    public JRadioButton getPin13() {
        return pin13;
    }

    public JRadioButton getPin14() {
        return pin14;
    }

    public JRadioButton getPin15() {
        return pin15;
    }

    public JRadioButton getPin16() {
        return pin16;
    }

    public JRadioButton getPin2() {
        return pin2;
    }

    public JRadioButton getPin3() {
        return pin3;
    }

    public JRadioButton getPin4() {
        return pin4;
    }

    public JRadioButton getPin5() {
        return pin5;
    }

    public JRadioButton getPin6() {
        return pin6;
    }

    public JRadioButton getPin7() {
        return pin7;
    }

    public JRadioButton getPin8() {
        return pin8;
    }

    public JRadioButton getPin9() {
        return pin9;
    }

    public boolean[] getPortFrameState() {
        boolean res[] = {getPin0().isSelected(), getPin1().isSelected(), getPin2().isSelected(), getPin3().isSelected(), getPin4().isSelected(), getPin5().isSelected(), getPin6().isSelected(), getPin7().isSelected(), getPin8().isSelected(), getPin9().isSelected(), getPin10().isSelected(), getPin11().isSelected(), getPin12().isSelected(), getPin13().isSelected(), getPin14().isSelected(), getPin15().isSelected(), getPin16().isSelected()};
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dummyPanel = new javax.swing.JPanel();
        pin8 = new javax.swing.JRadioButton();
        pin9 = new javax.swing.JRadioButton();
        pin7 = new javax.swing.JRadioButton();
        pin0 = new javax.swing.JRadioButton();
        pin2 = new javax.swing.JRadioButton();
        pin3 = new javax.swing.JRadioButton();
        pin12 = new javax.swing.JRadioButton();
        pin13 = new javax.swing.JRadioButton();
        pin14 = new javax.swing.JRadioButton();
        pin15 = new javax.swing.JRadioButton();
        pin16 = new javax.swing.JRadioButton();
        pin1 = new javax.swing.JRadioButton();
        pin4 = new javax.swing.JRadioButton();
        pin5 = new javax.swing.JRadioButton();
        pin6 = new javax.swing.JRadioButton();
        pin10 = new javax.swing.JRadioButton();
        pin11 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dummyPanel.setLayout(null);
        dummyPanel.add(pin8);
        pin8.setBounds(228, 117, 20, 18);
        dummyPanel.add(pin9);
        pin9.setBounds(228, 155, 20, 18);
        dummyPanel.add(pin7);
        pin7.setBounds(228, 193, 20, 18);
        dummyPanel.add(pin0);
        pin0.setBounds(228, 269, 20, 18);
        dummyPanel.add(pin2);
        pin2.setBounds(228, 306, 20, 18);
        dummyPanel.add(pin3);
        pin3.setBounds(228, 344, 20, 18);
        dummyPanel.add(pin12);
        pin12.setBounds(228, 420, 20, 18);
        dummyPanel.add(pin13);
        pin13.setBounds(228, 457, 20, 18);
        dummyPanel.add(pin14);
        pin14.setBounds(228, 495, 20, 18);
        dummyPanel.add(pin15);
        pin15.setBounds(265, 193, 20, 18);
        dummyPanel.add(pin16);
        pin16.setBounds(265, 231, 18, 18);
        dummyPanel.add(pin1);
        pin1.setBounds(265, 268, 18, 18);
        dummyPanel.add(pin4);
        pin4.setBounds(265, 344, 20, 18);
        dummyPanel.add(pin5);
        pin5.setBounds(265, 382, 18, 18);
        dummyPanel.add(pin6);
        pin6.setBounds(265, 457, 18, 18);
        dummyPanel.add(pin10);
        pin10.setBounds(265, 495, 20, 18);
        dummyPanel.add(pin11);
        pin11.setBounds(265, 533, 20, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info/nicola/jeremy/pi4jdemo/assets/p1header.png"))); // NOI18N
        dummyPanel.add(jLabel1);
        jLabel1.setBounds(0, -130, 500, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dummyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dummyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dummyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton pin0;
    private javax.swing.JRadioButton pin1;
    private javax.swing.JRadioButton pin10;
    private javax.swing.JRadioButton pin11;
    private javax.swing.JRadioButton pin12;
    private javax.swing.JRadioButton pin13;
    private javax.swing.JRadioButton pin14;
    private javax.swing.JRadioButton pin15;
    private javax.swing.JRadioButton pin16;
    private javax.swing.JRadioButton pin2;
    private javax.swing.JRadioButton pin3;
    private javax.swing.JRadioButton pin4;
    private javax.swing.JRadioButton pin5;
    private javax.swing.JRadioButton pin6;
    private javax.swing.JRadioButton pin7;
    private javax.swing.JRadioButton pin8;
    private javax.swing.JRadioButton pin9;
    // End of variables declaration//GEN-END:variables
}
